/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as ExtensionAuthRouteImport } from './routes/extension-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MusicIndexRouteImport } from './routes/music.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MusicSongsRouteImport } from './routes/music.songs'
import { Route as MusicPlaylistsRouteImport } from './routes/music.playlists'
import { Route as MusicPlatformsRouteImport } from './routes/music.platforms'
import { Route as MusicMatchingRouteImport } from './routes/music.matching'
import { Route as MediaReviewRouteImport } from './routes/media.review'
import { Route as MediaProvidersRouteImport } from './routes/media.providers'
import { Route as MediaLibraryRouteImport } from './routes/media.library'
import { Route as MusicPlaylistsIndexRouteImport } from './routes/music.playlists.index'
import { Route as MusicPlatformsIndexRouteImport } from './routes/music.platforms.index'
import { Route as MediaLibraryIndexRouteImport } from './routes/media.library.index'
import { Route as YoutubePlaylistsPlaylistIdRouteImport } from './routes/youtube.playlists.$playlistId'
import { Route as MusicPlaylistsPlaylistIdRouteImport } from './routes/music.playlists.$playlistId'
import { Route as MusicPlatformsSyncRouteImport } from './routes/music.platforms.sync'
import { Route as MusicPlatformsPlatformIdRouteImport } from './routes/music.platforms.$platformId'
import { Route as MediaLibraryEntryIdRouteImport } from './routes/media.library.$entryId'
import { Route as MusicPlatformsPlatformIdIndexRouteImport } from './routes/music.platforms.$platformId.index'
import { Route as MediaCatalogProviderIdProviderMediaIdRouteImport } from './routes/media.catalog.$providerId.$providerMediaId'
import { Route as MusicPlatformsPlatformIdPlaylistsPlaylistIdRouteImport } from './routes/music.platforms.$platformId.playlists.$playlistId'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionAuthRoute = ExtensionAuthRouteImport.update({
  id: '/extension-auth',
  path: '/extension-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MusicRoute,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRoute,
} as any)
const MusicSongsRoute = MusicSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => MusicRoute,
} as any)
const MusicPlaylistsRoute = MusicPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => MusicRoute,
} as any)
const MusicPlatformsRoute = MusicPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => MusicRoute,
} as any)
const MusicMatchingRoute = MusicMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => MusicRoute,
} as any)
const MediaReviewRoute = MediaReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => MediaRoute,
} as any)
const MediaProvidersRoute = MediaProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => MediaRoute,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MediaRoute,
} as any)
const MusicPlaylistsIndexRoute = MusicPlaylistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MusicPlaylistsRoute,
} as any)
const MusicPlatformsIndexRoute = MusicPlatformsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MusicPlatformsRoute,
} as any)
const MediaLibraryIndexRoute = MediaLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaLibraryRoute,
} as any)
const YoutubePlaylistsPlaylistIdRoute =
  YoutubePlaylistsPlaylistIdRouteImport.update({
    id: '/playlists/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => YoutubeRoute,
  } as any)
const MusicPlaylistsPlaylistIdRoute =
  MusicPlaylistsPlaylistIdRouteImport.update({
    id: '/$playlistId',
    path: '/$playlistId',
    getParentRoute: () => MusicPlaylistsRoute,
  } as any)
const MusicPlatformsSyncRoute = MusicPlatformsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => MusicPlatformsRoute,
} as any)
const MusicPlatformsPlatformIdRoute =
  MusicPlatformsPlatformIdRouteImport.update({
    id: '/$platformId',
    path: '/$platformId',
    getParentRoute: () => MusicPlatformsRoute,
  } as any)
const MediaLibraryEntryIdRoute = MediaLibraryEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => MediaLibraryRoute,
} as any)
const MusicPlatformsPlatformIdIndexRoute =
  MusicPlatformsPlatformIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MusicPlatformsPlatformIdRoute,
  } as any)
const MediaCatalogProviderIdProviderMediaIdRoute =
  MediaCatalogProviderIdProviderMediaIdRouteImport.update({
    id: '/catalog/$providerId/$providerMediaId',
    path: '/catalog/$providerId/$providerMediaId',
    getParentRoute: () => MediaRoute,
  } as any)
const MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute =
  MusicPlatformsPlatformIdPlaylistsPlaylistIdRouteImport.update({
    id: '/playlists/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => MusicPlatformsPlatformIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extension-auth': typeof ExtensionAuthRoute
  '/matching': typeof MatchingRoute
  '/media': typeof MediaRouteWithChildren
  '/music': typeof MusicRouteWithChildren
  '/youtube': typeof YoutubeRouteWithChildren
  '/media/library': typeof MediaLibraryRouteWithChildren
  '/media/providers': typeof MediaProvidersRoute
  '/media/review': typeof MediaReviewRoute
  '/music/matching': typeof MusicMatchingRoute
  '/music/platforms': typeof MusicPlatformsRouteWithChildren
  '/music/playlists': typeof MusicPlaylistsRouteWithChildren
  '/music/songs': typeof MusicSongsRoute
  '/media/': typeof MediaIndexRoute
  '/music/': typeof MusicIndexRoute
  '/media/library/$entryId': typeof MediaLibraryEntryIdRoute
  '/music/platforms/$platformId': typeof MusicPlatformsPlatformIdRouteWithChildren
  '/music/platforms/sync': typeof MusicPlatformsSyncRoute
  '/music/playlists/$playlistId': typeof MusicPlaylistsPlaylistIdRoute
  '/youtube/playlists/$playlistId': typeof YoutubePlaylistsPlaylistIdRoute
  '/media/library/': typeof MediaLibraryIndexRoute
  '/music/platforms/': typeof MusicPlatformsIndexRoute
  '/music/playlists/': typeof MusicPlaylistsIndexRoute
  '/media/catalog/$providerId/$providerMediaId': typeof MediaCatalogProviderIdProviderMediaIdRoute
  '/music/platforms/$platformId/': typeof MusicPlatformsPlatformIdIndexRoute
  '/music/platforms/$platformId/playlists/$playlistId': typeof MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extension-auth': typeof ExtensionAuthRoute
  '/matching': typeof MatchingRoute
  '/youtube': typeof YoutubeRouteWithChildren
  '/media/providers': typeof MediaProvidersRoute
  '/media/review': typeof MediaReviewRoute
  '/music/matching': typeof MusicMatchingRoute
  '/music/songs': typeof MusicSongsRoute
  '/media': typeof MediaIndexRoute
  '/music': typeof MusicIndexRoute
  '/media/library/$entryId': typeof MediaLibraryEntryIdRoute
  '/music/platforms/sync': typeof MusicPlatformsSyncRoute
  '/music/playlists/$playlistId': typeof MusicPlaylistsPlaylistIdRoute
  '/youtube/playlists/$playlistId': typeof YoutubePlaylistsPlaylistIdRoute
  '/media/library': typeof MediaLibraryIndexRoute
  '/music/platforms': typeof MusicPlatformsIndexRoute
  '/music/playlists': typeof MusicPlaylistsIndexRoute
  '/media/catalog/$providerId/$providerMediaId': typeof MediaCatalogProviderIdProviderMediaIdRoute
  '/music/platforms/$platformId': typeof MusicPlatformsPlatformIdIndexRoute
  '/music/platforms/$platformId/playlists/$playlistId': typeof MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extension-auth': typeof ExtensionAuthRoute
  '/matching': typeof MatchingRoute
  '/media': typeof MediaRouteWithChildren
  '/music': typeof MusicRouteWithChildren
  '/youtube': typeof YoutubeRouteWithChildren
  '/media/library': typeof MediaLibraryRouteWithChildren
  '/media/providers': typeof MediaProvidersRoute
  '/media/review': typeof MediaReviewRoute
  '/music/matching': typeof MusicMatchingRoute
  '/music/platforms': typeof MusicPlatformsRouteWithChildren
  '/music/playlists': typeof MusicPlaylistsRouteWithChildren
  '/music/songs': typeof MusicSongsRoute
  '/media/': typeof MediaIndexRoute
  '/music/': typeof MusicIndexRoute
  '/media/library/$entryId': typeof MediaLibraryEntryIdRoute
  '/music/platforms/$platformId': typeof MusicPlatformsPlatformIdRouteWithChildren
  '/music/platforms/sync': typeof MusicPlatformsSyncRoute
  '/music/playlists/$playlistId': typeof MusicPlaylistsPlaylistIdRoute
  '/youtube/playlists/$playlistId': typeof YoutubePlaylistsPlaylistIdRoute
  '/media/library/': typeof MediaLibraryIndexRoute
  '/music/platforms/': typeof MusicPlatformsIndexRoute
  '/music/playlists/': typeof MusicPlaylistsIndexRoute
  '/media/catalog/$providerId/$providerMediaId': typeof MediaCatalogProviderIdProviderMediaIdRoute
  '/music/platforms/$platformId/': typeof MusicPlatformsPlatformIdIndexRoute
  '/music/platforms/$platformId/playlists/$playlistId': typeof MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extension-auth'
    | '/matching'
    | '/media'
    | '/music'
    | '/youtube'
    | '/media/library'
    | '/media/providers'
    | '/media/review'
    | '/music/matching'
    | '/music/platforms'
    | '/music/playlists'
    | '/music/songs'
    | '/media/'
    | '/music/'
    | '/media/library/$entryId'
    | '/music/platforms/$platformId'
    | '/music/platforms/sync'
    | '/music/playlists/$playlistId'
    | '/youtube/playlists/$playlistId'
    | '/media/library/'
    | '/music/platforms/'
    | '/music/playlists/'
    | '/media/catalog/$providerId/$providerMediaId'
    | '/music/platforms/$platformId/'
    | '/music/platforms/$platformId/playlists/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extension-auth'
    | '/matching'
    | '/youtube'
    | '/media/providers'
    | '/media/review'
    | '/music/matching'
    | '/music/songs'
    | '/media'
    | '/music'
    | '/media/library/$entryId'
    | '/music/platforms/sync'
    | '/music/playlists/$playlistId'
    | '/youtube/playlists/$playlistId'
    | '/media/library'
    | '/music/platforms'
    | '/music/playlists'
    | '/media/catalog/$providerId/$providerMediaId'
    | '/music/platforms/$platformId'
    | '/music/platforms/$platformId/playlists/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/extension-auth'
    | '/matching'
    | '/media'
    | '/music'
    | '/youtube'
    | '/media/library'
    | '/media/providers'
    | '/media/review'
    | '/music/matching'
    | '/music/platforms'
    | '/music/playlists'
    | '/music/songs'
    | '/media/'
    | '/music/'
    | '/media/library/$entryId'
    | '/music/platforms/$platformId'
    | '/music/platforms/sync'
    | '/music/playlists/$playlistId'
    | '/youtube/playlists/$playlistId'
    | '/media/library/'
    | '/music/platforms/'
    | '/music/playlists/'
    | '/media/catalog/$providerId/$providerMediaId'
    | '/music/platforms/$platformId/'
    | '/music/platforms/$platformId/playlists/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionAuthRoute: typeof ExtensionAuthRoute
  MatchingRoute: typeof MatchingRoute
  MediaRoute: typeof MediaRouteWithChildren
  MusicRoute: typeof MusicRouteWithChildren
  YoutubeRoute: typeof YoutubeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension-auth': {
      id: '/extension-auth'
      path: '/extension-auth'
      fullPath: '/extension-auth'
      preLoaderRoute: typeof ExtensionAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof MusicRoute
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRoute
    }
    '/music/songs': {
      id: '/music/songs'
      path: '/songs'
      fullPath: '/music/songs'
      preLoaderRoute: typeof MusicSongsRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/playlists': {
      id: '/music/playlists'
      path: '/playlists'
      fullPath: '/music/playlists'
      preLoaderRoute: typeof MusicPlaylistsRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/platforms': {
      id: '/music/platforms'
      path: '/platforms'
      fullPath: '/music/platforms'
      preLoaderRoute: typeof MusicPlatformsRouteImport
      parentRoute: typeof MusicRoute
    }
    '/music/matching': {
      id: '/music/matching'
      path: '/matching'
      fullPath: '/music/matching'
      preLoaderRoute: typeof MusicMatchingRouteImport
      parentRoute: typeof MusicRoute
    }
    '/media/review': {
      id: '/media/review'
      path: '/review'
      fullPath: '/media/review'
      preLoaderRoute: typeof MediaReviewRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/providers': {
      id: '/media/providers'
      path: '/providers'
      fullPath: '/media/providers'
      preLoaderRoute: typeof MediaProvidersRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/library': {
      id: '/media/library'
      path: '/library'
      fullPath: '/media/library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof MediaRoute
    }
    '/music/playlists/': {
      id: '/music/playlists/'
      path: '/'
      fullPath: '/music/playlists/'
      preLoaderRoute: typeof MusicPlaylistsIndexRouteImport
      parentRoute: typeof MusicPlaylistsRoute
    }
    '/music/platforms/': {
      id: '/music/platforms/'
      path: '/'
      fullPath: '/music/platforms/'
      preLoaderRoute: typeof MusicPlatformsIndexRouteImport
      parentRoute: typeof MusicPlatformsRoute
    }
    '/media/library/': {
      id: '/media/library/'
      path: '/'
      fullPath: '/media/library/'
      preLoaderRoute: typeof MediaLibraryIndexRouteImport
      parentRoute: typeof MediaLibraryRoute
    }
    '/youtube/playlists/$playlistId': {
      id: '/youtube/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/youtube/playlists/$playlistId'
      preLoaderRoute: typeof YoutubePlaylistsPlaylistIdRouteImport
      parentRoute: typeof YoutubeRoute
    }
    '/music/playlists/$playlistId': {
      id: '/music/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/music/playlists/$playlistId'
      preLoaderRoute: typeof MusicPlaylistsPlaylistIdRouteImport
      parentRoute: typeof MusicPlaylistsRoute
    }
    '/music/platforms/sync': {
      id: '/music/platforms/sync'
      path: '/sync'
      fullPath: '/music/platforms/sync'
      preLoaderRoute: typeof MusicPlatformsSyncRouteImport
      parentRoute: typeof MusicPlatformsRoute
    }
    '/music/platforms/$platformId': {
      id: '/music/platforms/$platformId'
      path: '/$platformId'
      fullPath: '/music/platforms/$platformId'
      preLoaderRoute: typeof MusicPlatformsPlatformIdRouteImport
      parentRoute: typeof MusicPlatformsRoute
    }
    '/media/library/$entryId': {
      id: '/media/library/$entryId'
      path: '/$entryId'
      fullPath: '/media/library/$entryId'
      preLoaderRoute: typeof MediaLibraryEntryIdRouteImport
      parentRoute: typeof MediaLibraryRoute
    }
    '/music/platforms/$platformId/': {
      id: '/music/platforms/$platformId/'
      path: '/'
      fullPath: '/music/platforms/$platformId/'
      preLoaderRoute: typeof MusicPlatformsPlatformIdIndexRouteImport
      parentRoute: typeof MusicPlatformsPlatformIdRoute
    }
    '/media/catalog/$providerId/$providerMediaId': {
      id: '/media/catalog/$providerId/$providerMediaId'
      path: '/catalog/$providerId/$providerMediaId'
      fullPath: '/media/catalog/$providerId/$providerMediaId'
      preLoaderRoute: typeof MediaCatalogProviderIdProviderMediaIdRouteImport
      parentRoute: typeof MediaRoute
    }
    '/music/platforms/$platformId/playlists/$playlistId': {
      id: '/music/platforms/$platformId/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/music/platforms/$platformId/playlists/$playlistId'
      preLoaderRoute: typeof MusicPlatformsPlatformIdPlaylistsPlaylistIdRouteImport
      parentRoute: typeof MusicPlatformsPlatformIdRoute
    }
  }
}

interface MediaLibraryRouteChildren {
  MediaLibraryEntryIdRoute: typeof MediaLibraryEntryIdRoute
  MediaLibraryIndexRoute: typeof MediaLibraryIndexRoute
}

const MediaLibraryRouteChildren: MediaLibraryRouteChildren = {
  MediaLibraryEntryIdRoute: MediaLibraryEntryIdRoute,
  MediaLibraryIndexRoute: MediaLibraryIndexRoute,
}

const MediaLibraryRouteWithChildren = MediaLibraryRoute._addFileChildren(
  MediaLibraryRouteChildren,
)

interface MediaRouteChildren {
  MediaLibraryRoute: typeof MediaLibraryRouteWithChildren
  MediaProvidersRoute: typeof MediaProvidersRoute
  MediaReviewRoute: typeof MediaReviewRoute
  MediaIndexRoute: typeof MediaIndexRoute
  MediaCatalogProviderIdProviderMediaIdRoute: typeof MediaCatalogProviderIdProviderMediaIdRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaLibraryRoute: MediaLibraryRouteWithChildren,
  MediaProvidersRoute: MediaProvidersRoute,
  MediaReviewRoute: MediaReviewRoute,
  MediaIndexRoute: MediaIndexRoute,
  MediaCatalogProviderIdProviderMediaIdRoute:
    MediaCatalogProviderIdProviderMediaIdRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface MusicPlatformsPlatformIdRouteChildren {
  MusicPlatformsPlatformIdIndexRoute: typeof MusicPlatformsPlatformIdIndexRoute
  MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute: typeof MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute
}

const MusicPlatformsPlatformIdRouteChildren: MusicPlatformsPlatformIdRouteChildren =
  {
    MusicPlatformsPlatformIdIndexRoute: MusicPlatformsPlatformIdIndexRoute,
    MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute:
      MusicPlatformsPlatformIdPlaylistsPlaylistIdRoute,
  }

const MusicPlatformsPlatformIdRouteWithChildren =
  MusicPlatformsPlatformIdRoute._addFileChildren(
    MusicPlatformsPlatformIdRouteChildren,
  )

interface MusicPlatformsRouteChildren {
  MusicPlatformsPlatformIdRoute: typeof MusicPlatformsPlatformIdRouteWithChildren
  MusicPlatformsSyncRoute: typeof MusicPlatformsSyncRoute
  MusicPlatformsIndexRoute: typeof MusicPlatformsIndexRoute
}

const MusicPlatformsRouteChildren: MusicPlatformsRouteChildren = {
  MusicPlatformsPlatformIdRoute: MusicPlatformsPlatformIdRouteWithChildren,
  MusicPlatformsSyncRoute: MusicPlatformsSyncRoute,
  MusicPlatformsIndexRoute: MusicPlatformsIndexRoute,
}

const MusicPlatformsRouteWithChildren = MusicPlatformsRoute._addFileChildren(
  MusicPlatformsRouteChildren,
)

interface MusicPlaylistsRouteChildren {
  MusicPlaylistsPlaylistIdRoute: typeof MusicPlaylistsPlaylistIdRoute
  MusicPlaylistsIndexRoute: typeof MusicPlaylistsIndexRoute
}

const MusicPlaylistsRouteChildren: MusicPlaylistsRouteChildren = {
  MusicPlaylistsPlaylistIdRoute: MusicPlaylistsPlaylistIdRoute,
  MusicPlaylistsIndexRoute: MusicPlaylistsIndexRoute,
}

const MusicPlaylistsRouteWithChildren = MusicPlaylistsRoute._addFileChildren(
  MusicPlaylistsRouteChildren,
)

interface MusicRouteChildren {
  MusicMatchingRoute: typeof MusicMatchingRoute
  MusicPlatformsRoute: typeof MusicPlatformsRouteWithChildren
  MusicPlaylistsRoute: typeof MusicPlaylistsRouteWithChildren
  MusicSongsRoute: typeof MusicSongsRoute
  MusicIndexRoute: typeof MusicIndexRoute
}

const MusicRouteChildren: MusicRouteChildren = {
  MusicMatchingRoute: MusicMatchingRoute,
  MusicPlatformsRoute: MusicPlatformsRouteWithChildren,
  MusicPlaylistsRoute: MusicPlaylistsRouteWithChildren,
  MusicSongsRoute: MusicSongsRoute,
  MusicIndexRoute: MusicIndexRoute,
}

const MusicRouteWithChildren = MusicRoute._addFileChildren(MusicRouteChildren)

interface YoutubeRouteChildren {
  YoutubePlaylistsPlaylistIdRoute: typeof YoutubePlaylistsPlaylistIdRoute
}

const YoutubeRouteChildren: YoutubeRouteChildren = {
  YoutubePlaylistsPlaylistIdRoute: YoutubePlaylistsPlaylistIdRoute,
}

const YoutubeRouteWithChildren =
  YoutubeRoute._addFileChildren(YoutubeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionAuthRoute: ExtensionAuthRoute,
  MatchingRoute: MatchingRoute,
  MediaRoute: MediaRouteWithChildren,
  MusicRoute: MusicRouteWithChildren,
  YoutubeRoute: YoutubeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
