<Project Sdk="Aspire.AppHost.Sdk/13.3.0-preview.1.26226.2">

  <ItemGroup>
    <ProjectReference Include="..\Cantaro.Api\Cantaro.Api.csproj" />
    <ProjectReference Include="..\Cantaro.MigrationService\Cantaro.MigrationService.csproj" />
    <ProjectReference Include="..\Cantaro.ServiceDefaults\Cantaro.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.0-preview.1.26226.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.0-preview.1.26226.2" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Bun" Version="13.0.0-beta.439" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6597f638-7c32-43f8-a14c-2eeac21c8abe</UserSecretsId>
  </PropertyGroup>

</Project>
